version: '3'
services:
  scraper:
    build:
      context: ./crawler
    depends_on:
      - cassandra
    volumes:
      - ./data:/app/data
    environment:
      - CASSANDRA_HOST=172.17.0.2

  cassandra:
    build:
      context: ./cassandra
    networks:
      custom_network:
        ipv4_address: 172.17.0.2

networks:
  custom_network:
    ipam:
      config:
        - subnet: 172.17.0.0/16

